### ISSUE TITLE
After changing to minimal mode, black bar on top still shows

### ISSUE THREAD

**Issue by ColdMoonNight** [Eight-P/BD.8P#1]
![image](https://user-images.githubusercontent.com/77307545/117582061-d3990980-b0c5-11eb-80b2-bad296cf04dd.png)
Title says it all, even after turning minimal mode off, the black bar background thing still shows

**Comment by Eight-P** [comment]
Could you check with the newest versions T1 **`v0.4.23`** and ServerBar **`v0.4.42`** (bottom of the settings tab sidebar) if that issue is still present?

If yes, could you tell me what platform you are using (Windows, Mac, ...)?

**Comment by ColdMoonNight** [comment]
I'm using Linux. I just downloaded T1 from the BD site.
![image](https://user-images.githubusercontent.com/77307545/117663009-cfbcc400-b165-11eb-8eef-2c9885eea6b7.png)

**Comment by ColdMoonNight** [comment]
Nevermind, with a restart It works fine
