### ISSUE TITLE
All friends menu bug

### ISSUE THREAD

**Issue by poopermydooper1** [Eight-P/BD.8P#12]
### T1 Issue report:

when you try and scroll on the all friends menu in discord, you can only see the very top and when you try to scroll it starts glitching out and you can never get to the bottom

### T1 version:

0.7.3

### Discord client:

Stable (Default)

### Platform:

Windows

### Discord Mod:

BetterDiscord

**Comment by Eight-P** [comment]
Thanks for letting me know. 
I reversed some stuff with v0.5.57. It should at least work again. 
Please let me know if there are any more issues.
