### ISSUE TITLE
the theme is broken pls fix it this is my fav theme

### ISSUE THREAD

**Issue by Eray761** [Eight-P/BD.8P#15]
### T1 Issue report:

![image](https://user-images.githubusercontent.com/89261868/222265442-b2012ce4-96ea-4909-8ccb-8cdfbb3468ea.png)

### T1 version:

v0.8

### Discord client:

Stable (Default)

### Platform:

Windows

### Discord Mod:

BetterDiscord

### Additional notes:

best theme ever

**Comment by Eight-P** [comment]
should be fixed now. thank you

**Comment by Eray761** [comment]
![image](https://user-images.githubusercontent.com/89261868/222743747-c0de0bcf-1ef7-4445-9532-e8d770c577fe.png)
well that one is fixed but i now the background is like that i mean its not that annoying atleast not as annoying as the other one i sent

**Comment by Eray761** [comment]
![image](https://user-images.githubusercontent.com/89261868/222744090-d5423f6d-b5e7-4a2f-99ed-7d17eebade54.png)
and the profile preview seems to be a bit broken not sure if that also happened after the fix

**Comment by Eray761** [comment]
nope not caused by another plugin or custom css im only using t1 so not caused by another theme aswell

**Comment by Eray761** [comment]
i didnt touch custom css anyways

**Comment by Eray761** [comment]
oh wait my bad i just realized while redownloading the theme i forgot the theme i used after turning t1 off i can be dumb sometimes srry

**Comment by Eray761** [comment]
the profile preview isnt because of that btw

**Comment by Eight-P** [comment]
> the profile preview isnt because of that btw

yup, should be fixed now.
