### ISSUE TITLE
Visual Bug

### ISSUE THREAD

**Issue by JOADTORO06** [Eight-P/BD.8P#16]
### T1 Issue report:

![image](https://user-images.githubusercontent.com/113266629/222286548-9989f139-c849-4738-b47c-afad510cd365.png)
This icons are bug, change it please.

### T1 version:

v0.8

### Discord client:

Stable (Default)

### Platform:

Windows

### Discord Mod:

BetterDiscord

**Comment by Eight-P** [comment]
should be fixed now.

**Comment by JOADTORO06** [comment]
thanks.
