### ISSUE TITLE
Text Animation + Margins

### ISSUE THREAD

**Issue by AlarkiusJay** [Eight-P/BD.8P#2]
Great theme, just a slight margin error (?) If you can call this one? idk lol
I don't know about you or if others have encountered this, but the default discord theme has this little text animation appear at the bottom of the text area. Don't know if the author did a mistake but this was one thing is bugging me honestly lmao
@Eight-P 

Maybe perhaps adding a small banner that perfectly aligns with chat. 

Also overlaps with text either in DMs or server chats-
Author, if you happen to see this, let me know!

![Screenshot (67)](https://user-images.githubusercontent.com/84819182/119582709-e3794480-bd79-11eb-9edd-7e14a436a7be.png)

**Comment by Eight-P** [comment]
The position of that typing indicator is intended as the said space at the bottom that Discord has by default is not there in the T1 Theme. And tbh I find it totally fine where it is now. The overlapping tho should be improved as of:  eb9800184658171f9739437ad6155bc7c2916208
