### ISSUE TITLE
Discord Had an Update?

### ISSUE THREAD

**Issue by JohannKili** [Eight-P/BD.8P#21]
### T1 Issue report:

The background is not loading (discord update?)

![image](https://github.com/Eight-P/BD.8P/assets/139029143/4675225f-02cf-4ad7-bcfd-2ae29f3655c7)

### T1 version:

0.8

### Discord client:

PTB

### Platform:

Windows

### Discord Mod:

BetterDiscord

**Comment by Eight-P** [comment]
Yes, Discord pushed a big update changing lots of internal things, which broke tons of stuff.
Expect it to take a while before things are fully fixed.

**Comment by Eight-P** [comment]
T1 should work again.

**Comment by Eight-P** [comment]
There are some minor issues I'll iron out with some of the next updates and I have not checked any plugin compatibility so far. But it should be like 90% functional.
