### ISSUE TITLE
Servers are gone?

### ISSUE THREAD

**Issue by skyisthela** [Eight-P/BD.8P#22]
### T1 Issue report:

![image](https://github.com/Eight-P/BD.8P/assets/150245867/d788331c-6595-41ae-8207-1b923190cdf9)
not sure what the issue is, but the server icons disappear. when i first startup the client they do appear (only some) but once i click on them it goes away, i can still interact with them but can't see them at all

### T1 version:

0.8.1

### Discord client:

Stable (Default)

### Platform:

Windows

### Discord Mod:

Other (list below)

### Additional notes:

vencord

**Comment by Eight-P** [comment]
I don't seem to be able to replicate this issue.
Please make sure it's not caused by something else.

**Comment by skyisthela** [comment]
> I don't seem to be able to replicate this issue. Please make sure it's not caused by something else.

hey i apologize, it seems it's an issue with *VESKTOP *specifically, i thought they were the same thing, i did a clean reinstall of vesktop and the issue persisted but not on vencord.
