### ISSUE TITLE
Turned the theme upside down

### ISSUE THREAD

**Issue by Scorpions95** [Eight-P/BD.8P#25]
### T1 Issue report:

Turned the theme upside down
check the image here ----> https://prnt.sc/JxqTiabpz8Gv
![image](https://github.com/Eight-P/BD.8P/assets/24534657/0383231b-2111-4fb8-89cc-141007e6826f)

### T1 version:

v0.8.1

### Discord client:

PTB

### Platform:

Windows

### Discord Mod:

BetterDiscord

### Additional notes:

This happen after i update discord

**Comment by Eight-P** [comment]
Yeah, the update broke it, but there is a good chance they'll revert it again.
Stable seems unaffected.
If you need to access the settings menu, do Ctrl + Comma

**Comment by Scorpions95** [comment]
even normal discord broke the theme with updates ;-;
can you make update of the theme maybe this prevent to stop broking

**Comment by Eight-P** [comment]
should work again

**Comment by Scorpions95** [comment]
yes!
thank you, it work now
appriciated your work !

**Comment by BlannyBlannyBlanc** [comment]
I also get the same issue, thank you
