### ISSUE TITLE
Prank theme or extremely broken on purpose?

### ISSUE THREAD

**Issue by BlannyBlannyBlanc** [Eight-P/BD.8P#26]
### T1 Issue report:

Is this theme broken on purpose? because when I activate it, I just get a single bar on the top and can't use anything else; rendering Discord unusable.

### T1 version:

0.8.1

### Discord client:

Stable (Default)

### Platform:

Windows

### Discord Mod:

Other (list below)

### Additional notes:

Vencord

**Comment by Scorpions95** [comment]
Same as me https://github.com/Eight-P/BD.8P/issues/25
