### ISSUE TITLE
[BUG] Missing screen share button

### ISSUE THREAD

**Issue by Mickxz** [Eight-P/BD.8P#3]
**Please describe the issue in detail and how to reproduce it, (preferably with screenshots).**
The screenshare button is missing on the HUD unless you're using a compatible application or game.
Hence im not able to stream discord or the screen itself unless i open a game to start screen sharing and then switching the screen like i normally would on basic discord.

**Please include as much information as possible:**

1. Which version of T1 do you have? (Themes tab and bottom of the user settings sidebar)

v0.7.3
2. Which Discord client are you using? (Stable, PTB, Canary, ..)

Stable 
3. Which platform are you on? (Windows, Mac, Linux, ...)

Windows
4. Which Discord Mod are you using? (BetterDiscord, Powercord, Vizality, ...)

BD
5. Do you have any other additional Themes or Plugins enabled?
BDFDB v1.8.4
NitroPerks v1.3.6
PluginRepo v2.2.6
ShowHiddenChannels v3.0.2
ThemeRepo v2.2.7
ZeresPluginLibrary v1.2.32

**Comment by Eight-P** [comment]
Thanks for reporting.

To screenshare:
Join a voice channel, then click the channel again. 
You’ll see that call view which has the “Share your screen” button at the bottom.

Sorry for any inconvenience.

**Comment by Mickxz** [comment]
I figured it out later after my post hahaha. I didn't want to close it since i didn't know if it was intended to be missing que button that's present on the normal discord theme . Anyway thanks for the great theme and for the fast response :).

**Comment by Eight-P** [comment]
No problem, I appreciate every report.

Btw, I’d be careful with plugins like NitroPerks.
Not every plugin is safe to use.
With some you can get your Discord account banned.
And I, although not 100% sure believe that is one of them.

**Comment by Mickxz** [comment]
Hey, sorry for not replying, i thought i had posted my reply but i guess not. I saw what you did with the theme now and it's looking sick. Great job with it! and also thanks for caring about the feedback.
