### ISSUE TITLE
could you fix this bug? i can't read da text

### ISSUE THREAD

**Issue by sawtoothtulip86** [Eight-P/BD.8P#31]
### T1 Issue report:

da text shows like this
![image_2024-12-22_170800059](https://github.com/user-attachments/assets/c56b644e-4ed2-47fc-a152-e8910fa99dda)

### Discord client:

Stable (Default)

### Discord Mod:

Vencord

### Platform:

Windows

### T1 version:

Version: 0.8.2

**Comment by Eight-P** [comment]
What's the name of the plugin(s) that add these?

**Comment by sawtoothtulip86** [comment]
> What's the name of the plugin(s) that add these?

it's called "ServerListIndicators" if I was right

**Comment by Eight-P** [comment]
I gave it a go, and it should be a bit better now; let me know.
Unfortunately, the way the server bar is themed and horizontal, it creates some limitations when it comes to these type of additions.

**Comment by sawtoothtulip86** [comment]
> I gave it a go, and it should be a bit better now; let me know. Unfortunately, the way the server bar is themed and horizontal, it creates some limitations when it comes to these type of additions.

thx for fixing that bug
