### ISSUE TITLE
[BUG] Missing disconnect button if channel name string is too long.

### ISSUE THREAD

**Issue by Mickxz** [Eight-P/BD.8P#4]
**Please describe the issue in detail and how to reproduce it, (preferably with screenshots).**
Hey is me again :), i'm loving all about this theme and i wanted to give you some feedback about a bug that i found today while switching between some channels on my discord server.

The thing is that when you enter a channel with a long name, the button to disconnect from that channel will disappear because of the offset. 

https://imgur.com/a/ByXnwon

I know a little about programming so i think a quick fix for this would be to verify the len of the channel name string and shorten it when is surpasses a certain amount of characters  

**Please include as much information as possible:**

1. Which version of T1 do you have? (Themes tab and bottom of the user settings sidebar)
T1 v0.7.3

2. Which Discord client are you using? (Stable, PTB, Canary, ..)
Stable 

3. Which platform are you on? (Windows, Mac, Linux, ...)
Windows

4. Which Discord Mod are you using? (BetterDiscord, Powercord, Vizality, ...)
BT

5. Do you have any other additional Themes or Plugins enabled?
BDFDB v1.8.4
PluginRepo v2.2.6
ShowHiddenChannels v3.0.2
ThemeRepo v2.2.7
ZeresPluginLibrary v1.2.32

**Comment by Eight-P** [comment]
Should be fixed now.
Thanks again
