### ISSUE TITLE
Discord bottom part

### ISSUE THREAD

**Issue by mido933** [Eight-P/BD.8P#8]
### T1 Issue report:

![Screenshot_1](https://user-images.githubusercontent.com/88627986/139816208-84699f15-9234-41a5-aa4a-ff6fc268d8fa.png)

### T1 version:

v0.5.374

### Discord client:

Stable (Default)

### Platform:

Windows

### Discord Mod:

BetterDiscord

**Comment by Eight-P** [comment]
Should be fixed, thanks for letting me know.

idk what Discord is doing. It's possible they'll break it again, and i'm not home for a week, but I'll try my best.

**Comment by mido933** [comment]
Thank you for the fix. just found the theme yday and i love it. thank you for hard work ❤️

**Comment by ItsLeon15** [comment]
Just wanted to say that I also got this issue with the sideways server selection. 

Thanks for fixing this issue
